/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TailoringRouteImport } from './routes/tailoring'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'

const TailoringRoute = TailoringRouteImport.update({
  id: '/tailoring',
  path: '/tailoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/tailoring': typeof TailoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/tailoring': typeof TailoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/tailoring': typeof TailoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/collections'
    | '/contact'
    | '/explore'
    | '/pricing'
    | '/tailoring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/collections'
    | '/contact'
    | '/explore'
    | '/pricing'
    | '/tailoring'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/collections'
    | '/contact'
    | '/explore'
    | '/pricing'
    | '/tailoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  PricingRoute: typeof PricingRoute
  TailoringRoute: typeof TailoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tailoring': {
      id: '/tailoring'
      path: '/tailoring'
      fullPath: '/tailoring'
      preLoaderRoute: typeof TailoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  PricingRoute: PricingRoute,
  TailoringRoute: TailoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
